# Generated by Django 3.1.2 on 2021-01-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210113_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
    ]
