# Generated by Django 3.1.2 on 2021-01-13 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_like_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='users',
        ),
        migrations.AddField(
            model_name='follow',
            name='followed',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ManyToManyField(related_name='others', to=settings.AUTH_USER_MODEL),
        ),
    ]
