# Generated by Django 3.1.2 on 2021-01-14 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210113_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
